### ISSUE TITLE
Problems with AK4552 (AK4556 compatible)

### ISSUE THREAD

**Issue by DatanoiseTV** [garygru/yummyDSP#1] opened 2020-10-31 12:25 UTC
I've tried it on a audio dev board I've made and which works good with other examples, but the synth example
doesn't run.

Also, the problem is I'm not sure now to set the mode for the DAC to LSB and ADC to MSB, as this is the weird thing the AK4552 uses. 

```
	static const i2s_config_t i2s_config = {
				.mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_TX),
				.sample_rate = fs,
				.bits_per_sample = I2S_BITS_PER_SAMPLE_24BIT,
				.channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT, // switch to left only?
				.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_LSB),
				.intr_alloc_flags = ESP_INTR_FLAG_LEVEL1, // high interrupt priority
				.dma_buf_count = 2,
				.dma_buf_len = AudioDriver::BufferSize,
				.use_apll = true,
				.tx_desc_auto_clear = true,
				.fixed_mclk = mclk_rate
		};
```

**Comment by DatanoiseTV** [comment] 2020-10-31 12:48
Solved: DIN / DOUT were swapped.

**Comment by garygru** [comment] 2020-10-31 17:28
El clásico. 
Btw. AK4552 datasheet says MSB and LSB _justified_ not to mix up with MSB and LSB first. Bot DAC and ADC are MSB first. So you just have to shift 8 bits if anything.

**Comment by DatanoiseTV** [comment] 2020-11-01 09:32
@garygru Thanks for the tip. Can you give me some quick help to get both the ADC and DAC up and running at 24-bit 48KHz with YummyDSP? That would be great. Somehow I can't get it to work properly.

**Comment by garygru** [comment] 2020-11-02 10:03
Hey, first of all your Codec/EvalBoard should be in slave mode i.e. the ESP32 is generating the master clock (otherwise you have to change the I2S configuration). 

The AK4552 is compatible with the AK4556 as long as the later is configured to run in "Mode 0" which is the weird LJ/RJ combination (see AK4556 data sheet). My first thought was that yummyDSP is expecting I2S configuration which is both input and output left adjusted. But having a look at _Audiodriver::floatToInt()_ it should work with exactly this config. 
Nevertheless this is the point to do some shifting action if required. 

Have a scope or a logic analyser at hand? Then you could check bit alignment to the LRCLK with some dummy data. 
Of course checking MCLK and other clocks and data signals with a scope would be the first step. 

Good luck

**Comment by DatanoiseTV** [comment] 2020-11-02 10:41
@garygru So it is in slave mode with MCLK coming from GPIO0. Audio Output works all properly, but I had to set .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_LSB), to make it work.
I have a logic analyzer, but the problem is that I don't have any test points on the PCB I made, so measuring will be a bit of a problem. So if the DAC is LSB justified and the ADC MSB, I need to swap the endianess?

**Comment by garygru** [comment] 2020-11-02 23:19
@DatanoiseTV that's weird but I've found this [issue](https://github.com/espressif/esp-idf/issues/4957) which could explain it. 
IMO you don't need to swap endianness. Try to left shift or right shift the integer samples by 8 (e.g. y = (y << 8) or y = (y >> 8) in _intToFloat()_ for esp input and _floatToInt()_ for output respectively). Have a look at the scaling and constraints also.

**Comment by DatanoiseTV** [comment] 2020-11-02 23:29
@garygru Oh wow, that issue is really weird. I will try asap.

**Comment by garygru** [comment] 2020-11-03 09:45
Yep, it's in readSample() in the header.

**Comment by DatanoiseTV** [comment] 2020-11-04 16:30
@garygru So I've stayed with LSB output mode and audio input works, but it's tiny bit oversaturated / distorted even with low signal levels. Any idea?

**Comment by DatanoiseTV** [comment] 2020-11-04 17:09
@garygru Could you give me your schematic as image or PDF? got a AK4556 now on my board, but i have all CKS pins to 0 (LJ/RJ mode). Cannot open it with my KiCad Nightly.

**Comment by garygru** [comment] 2020-11-05 09:35
@DatanoiseTV to be honest my codec module was wired to an ESP32 on a breadboard and I can't remember if I've switched the CKS pins or pulled them hi or lo somehow. 
saturation / distortion sounds like shifting scaling error. A logic analyser would help here. Try to solder a few debug wires to the codec pins if you don't have small test clips. 

Anyways, just a shot in the dark:
```
float int2Float(int32_t sample) {
	return (float)((sample >> 8) * AudioDriver::ScaleInt2Float);
}
```

**Comment by DatanoiseTV** [comment] 2020-11-05 11:17
I'm not really sure that the problem is
https://i.imgur.com/SA6aMVL.png

**Comment by DatanoiseTV** [comment] 2020-11-05 12:59
@garygru By the way, if you send me a shipping address, I'll send you my assembled dev board with 3.3V Digital, 3.3V Analog LDO, ESP32-WROVER32-E (with Silicon V3), AK4552 codec and USB-Serial on Board. Maybe that makes it easier and you have something to play with.

**Comment by GazTurtle** [comment] 2020-11-05 13:05
I'm ready all the comments,I'm about to start similar work 👍

**Comment by garygru** [comment] 2020-11-05 14:23
@DatanoiseTV SDTO looks misaligned (or swapped with SDTI?) when comparing to the datasheet. That is confusing because it‘s the output of the codec which should behave like in the datasheet. Sure a dev board would be great and make things much easier!  Von: DatanoiseGesendet: Donnerstag, 5. November 2020 12:1An: garygru/yummyDSPCc: Gary Grutzek; MentionBetreff: Re: [garygru/yummyDSP] Problems with AK4552 (AK4556 compatible) (#1) I'm not really sure that the problem ishttps://i.imgur.com/SA6aMVL.png—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DatanoiseTV** [comment] 2020-11-05 19:51
@garygru Ok cool just drop be your address to (de.retrospektive) at gmail and I will get one ready for you. Hopefully we can tackle the problem then.

**Comment by DatanoiseTV** [comment] 2020-11-06 08:18
@garygru Just finished soldering the board for you! https://drive.google.com/file/d/118G9pDzQFQp-aJs-4dhhq31kqN_Tk3aj/view?usp=sharing

**Comment by garygru** [comment] 2020-11-06 09:21
Great, thanks. I'll drop you a line. 
I'm sure we get that tackled down!
 
Btw. I've found an image showing CKS pin 2 pulled high. This translates to standard I2S format (mode 4). 
![7001781558467953820](https://user-images.githubusercontent.com/1721790/98348978-b8b3e280-2019-11eb-8d01-d5dc596eab04.jpg)

**Comment by DatanoiseTV** [comment] 2020-11-06 09:25
@garygru Thx! If you send it via mail in the next 10m, I'm going outside now and can ship it immediately.
I'd like to keep mode to LJ/RJ for now to make it AK4552 compatible. I'm sending you the AK4552 version, as 4556 are sold out (AKM factory burnt down).

**Comment by garygru** [comment] 2020-11-06 09:31
Great, Mail is out. I'm also heading to be compatible to several alignments and formats. LJ/RJ and I2S would be good staring point.

**Comment by garygru** [comment] 2020-11-23 17:33
Fixed with last commit

**Closed by garygru** 2020-11-23 17:33 UTC
